name: Build, Convert, and Publish Package

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ["3.10", "3.12"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine Cython
    
    - name: Build .so files
      run: |
        # Create a version-specific build directory
        BUILD_DIR=build_${{ matrix.python-version }}
        mkdir -p $BUILD_DIR
        
        # Convert Python files to .so using Cython
        python setup.py build_ext --inplace
        
        # Copy .so files to the build directory
        find . -name "*.so" -exec cp {} $BUILD_DIR/ \;
        
        # Copy setup.py and other necessary files
        cp setup.py $BUILD_DIR/
        cp README.md $BUILD_DIR/
        cp requirements.txt $BUILD_DIR/
    
    - name: Build distribution packages
      run: |
        cd $BUILD_DIR
        python setup.py sdist bdist_wheel
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: $BUILD_DIR/dist

    - name: Clean up
      if: always()
      run: |
        rm -rf build_${{ matrix.python-version }}
        rm -rf build
        rm -rf dist
        rm -rf *.egg-info
